#!/usr/bin/env python3
"""
Compiles content.md into the CONTENT block inside index.html.

Usage: python3 build.py
Run this from the Jonas_Defense folder any time you edit content.md.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
CONTENT_MD = HERE / "content.md"
INDEX_HTML = HERE / "index.html"

START_MARKER = "/* === CONTENT START (generated by build.py from content.md — do not hand-edit) === */"
END_MARKER = "/* === CONTENT END === */"


def parse_content_md(text):
    scenes = {}
    scene_id = None
    field = None
    list_mode = False
    buf = []

    def flush_field():
        nonlocal field, buf, list_mode
        if scene_id is not None and field is not None:
            if list_mode:
                scenes[scene_id][field] = [l[2:].strip() for l in buf if l.strip()]
            else:
                joined = " ".join(l.strip() for l in buf if l.strip() != "")
                scenes[scene_id][field] = joined.strip()
        field = None
        buf = []
        list_mode = False

    for raw_line in text.splitlines():
        line = raw_line.rstrip("\n")
        heading_match = re.match(r"^##\s+(\S+)\s*$", line)
        field_match = re.match(r"^\*\*([A-Za-z0-9]+):\*\*\s?(.*)$", line)

        if heading_match:
            flush_field()
            scene_id = heading_match.group(1)
            scenes[scene_id] = {}
            continue

        if field_match:
            flush_field()
            field = field_match.group(1)
            list_mode = (field == "List")
            first_val = field_match.group(2)
            if first_val.strip():
                buf.append(first_val)
            continue

        if scene_id is None or field is None:
            continue  # preamble / outside any field, ignore

        buf.append(line)

    flush_field()
    return scenes


def main():
    if not CONTENT_MD.exists():
        print(f"error: {CONTENT_MD} not found", file=sys.stderr)
        sys.exit(1)
    if not INDEX_HTML.exists():
        print(f"error: {INDEX_HTML} not found", file=sys.stderr)
        sys.exit(1)

    md_text = CONTENT_MD.read_text(encoding="utf-8")
    scenes = parse_content_md(md_text)

    html = INDEX_HTML.read_text(encoding="utf-8")
    if START_MARKER not in html or END_MARKER not in html:
        print("error: CONTENT markers not found in index.html — did the file structure change?", file=sys.stderr)
        sys.exit(1)

    before, rest = html.split(START_MARKER, 1)
    _, after = rest.split(END_MARKER, 1)

    content_js = json.dumps(scenes, ensure_ascii=False, indent=2)
    new_block = f"{START_MARKER}\n    const CONTENT = {content_js};\n    {END_MARKER}"

    new_html = before + new_block + after
    INDEX_HTML.write_text(new_html, encoding="utf-8")

    print(f"Compiled {len(scenes)} scenes from content.md into index.html:")
    for sid in scenes:
        print(f"  - {sid}")


if __name__ == "__main__":
    main()
